### PR TITLE
Add black (#55)

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by abitrolly** [comment]
Waiting for reply.. https://forum.snapcraft.io/t/updating-black/11078

**Comment by apriha** [comment]
Good idea, thanks! How about installing from pip and running black on just Python 3.6 and/or 3.7?

**Comment by abitrolly** [comment]
Should be no problem, just need a bash condition check on Python version in
Travis.

**Comment by apriha** [comment]
Sounds good. I'll update the config to run that on just Python 3.6/3.7. Thanks again!

**Pull request merged**
